### ISSUE TITLE
Poll closing date

### ISSUE THREAD

**Issue by theneurasthenicrat** [theneurasthenicrat/whale4#1]
- The poll closing date should rather be in "Advanced parameters" (not in general parameters), as most people do not care about it.
- There should be a time with the date
- By default, the closing date should be very far in the future (so for that people who don't bother setting the closing date the poll remains virtually open forever)
- In the poll parameters (once the poll is created), there should be a button "close now" to fix the closing date to now.

**Comment by natetem** [comment]
- I put the closing date in Advanced parameters.
- By default, i set the closing date at 3 years from creation date
- I will try to add a button for close now.

**Comment by natetem** [comment]
I put an option for closing date
