### ISSUE TITLE
curl: SSL certificate problem

### ISSUE THREAD

**Issue by oliviercailloux** [theneurasthenicrat/whale4#12]
Hi!

The web site seems to fail curl certificate verification.

curl -I 'https://whale.imag.fr/'
curl: (60) SSL certificate problem: unable to get local issuer certificate

Slightly annoying as it causes packages that verify for broken urls to warn against `https://whale.imag.fr/`.

**Comment by DominikPeters** [comment]
Getting this error too. Browser complains that the certificate has expired recently.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/3543224/178267363-79c3ace5-e01e-4a86-96d8-11372c206fbc.png">

**Comment by theneurasthenicrat** [comment]
The certificate problem seems to be fixed (until next year...). Doesn't depend on me but on the lab tech staff.
