### ISSUE TITLE
Invite emails can't be sent, bad SMTP credentials

### ISSUE THREAD

**Issue by DominikPeters** [theneurasthenicrat/whale4#14]
Trying to invite participants to a secret poll fails. Error message: `(535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials x5-20020adff0c5000000b0021d6d9c0bd9sm5699517wro.82 - gsmtp')`

Also, it is probably a good idea not to run the public instance with `DEBUG = true`.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/3543224/178268811-761fec30-9676-4bc2-ae48-eaa818ac2cce.png">

**Comment by theneurasthenicrat** [comment]
The credentials are OK, but there are security issues due to Google's new security policy. Gmail now does not accept connections from less secured applications (like a Python application) anymore. I am still searching for another solution, but it will take time...

**Comment by DominikPeters** [comment]
You could try setting an app password under https://myaccount.google.com/security

See https://support.google.com/accounts/answer/185833?hl=en

**Comment by theneurasthenicrat** [comment]
I changed the SMTP provider. That should solve the problem.
