### ISSUE TITLE
Add / remove candidates - I don't know

### ISSUE THREAD

**Issue by theneurasthenicrat** [theneurasthenicrat/whale4#3]
If vote has already started (i.e. somebody has already voted):
- if Add/remove candidates is not allowed, it should be indeed forbidden
- if I don't know is not allowed, it should be forbidden to add another candidate (however, removing candidates should be OK)

Be careful: when removing candidates, the underlying linear orders should be consistent.

**Comment by natetem** [comment]
Correct this issue
