### ISSUE TITLE
Shuffle candidates

### ISSUE THREAD

**Issue by theneurasthenicrat** [theneurasthenicrat/whale4#5]
There should be an option in the set of advanced options to shuffle the candidates when they are displayed to the voters.

**Comment by natetem** [comment]
I do not understand the purpose of this option

**Comment by theneurasthenicrat** [comment]
- Add a Boolean option in the set of advanced options for a poll.
- If this option is activated (set to "yes"), then, each time the voting page is loaded (not the poll page, the voting page), the candidates appear in a different order.

**Comment by natetem** [comment]
I add an option of shuffle the candidates in voting page. But i have a problem in view poll: Candidates are not ordered.
