### ISSUE TITLE
Dataviz: styling issues

### ISSUE THREAD

**Issue by theneurasthenicrat** [theneurasthenicrat/whale4#9]
- In the graphs showing scoring methods the axes should be in the foreground (and the bars in the background).
- In all the graphs, the svg should be as large as the whole graph container.
- Scoring methods again: if possible, the transition between the different graphs (bars height) should be smooth (as in Whale 3).

**Comment by natetem** [comment]
About the size of svg, is use width =window.innerWidth/2  and  height = window.innerHeight/2. 
Should i change the size with 100%?

**Comment by theneurasthenicrat** [comment]
Setting the width to 100% won't work (you should provide a size in pixels, just as you do). What you should probably do is use a Javascript function to get the size (width and height) of the enclosing container (div#graph) at page load and after each resize event and use it to compute the width and height of the svg element.

**Comment by natetem** [comment]
I use JavaScript functions width and height.
